version: '3.8'

services:
  db_customer:
    container_name: db_customer
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./docker/db_customer:/var/lib/mysql
    ports:
      - '3307:3306'
    restart: always
  db_provider:
    container_name: db_provider
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./docker/db_provider:/var/lib/mysql
    ports:
      - '3308:3306'
    restart: always
  db_check:
    depends_on:
      - db_customer
      - db_provider
    container_name: db_check
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./docker/db_check:/var/lib/mysql
    ports:
      - '3309:3306'
    restart: always
  admin_mysql:
    depends_on:
      - db_customer
      - db_provider
      - db_check
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '3306:80'
    restart: always
  zipkin_server:
    depends_on:
      - storage-aux-container
    container_name: zipkin_server
    image: openzipkin/zipkin-slim
    environment:
      - STORAGE_TYPE=mem
    ports:
      - '9411:9411'
    restart: always
  storage-aux-container:
    image: busybox:1.31.0
    container_name: storage-aux-container

volumes:
  db_customer:
  db_provider:
  db_check: