server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodribatista/cheque-agro.git
          default-label: "main"
          search-paths: config-data
          #username: ${GIT_USERNAME}
          #password: ${GIT_TOKEN}
          force-pull: true